import React from 'react';
import Head from 'next/head';

const Home: React.FC = () => (
    <div style={{ height: '100%' }}>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
            <p>Template page</p>
        </main>
    </div>
);

export default Home;
